### ISSUE TITLE
pixel size snapping back

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#102]
When a reduced pixel size  is selected, and then you (i) zoom in, or (ii)  choose a new start date, or (iii) choose new reference point,  the pixel size always snaps back to full size.

Try this dataset:

http://149.165.153.50/start/0.7573/-77.9003/11.8499?flyToDatasetCenter=false&startDataset=S1_IW12_120_1183_1185_20170112_20171226_N00539_N00953_W078148_W077744

<img width="1076" alt="image" src="https://github.com/user-attachments/assets/ae5ac4ef-f279-426d-ba39-c499e645dbd8">

**Comment by stackTom** [comment]
Fix attempt in this commit: https://github.com/geodesymiami/insarmaps/commit/49c2891de246399f5494743883320b724d9d56e7

Let me know if its fixed, seems like it to me.

**Comment by falkamelung** [comment]
I tried on *50 which seems updated on tileserverDevelopment branch.

It works fine for zooming in and out, but for selecting reference point and different startDate it still snaps back to original size.

**Comment by stackTom** [comment]
Can you try to fully clear your cache? Or use an incognito window or a different browser. On my system it's working fine. Otherwise, please send me a link so I can try to reproduce it.

**Comment by falkamelung** [comment]
Yes, you are right. There is no problem after emptying the cache. My bad.

I discovered one issue, however.  If you switch to satellite as background image it still snaps back:
https://github.com/user-attachments/assets/0a8434c1-939c-4e07-a7ea-6185abf06a0c

In  any case,  the possibility to adjust the pixel size is fantastic.  It offers  new opportunities for interpreting the data. Thank you!

**Comment by stackTom** [comment]
> 49c2891

Fixed in https://github.com/geodesymiami/insarmaps/commit/8833791d887914e540de0e42dc4f3136fd1313c3
Closing this issue, please reopen if issue persists.
