### ISSUE TITLE
Don't recolor when no new points rendered

### ISSUE THREAD

**Issue by stackTom** [geodesymiami/insarmaps#109]
Currently, if we have a reference point or custom dates, we recolor on every map movement or zoom change. Even if the resultant movement/zoom change does not lead to new being points being rendered.

We need to fix this - only recolor/re-download data from the server if the user interaction leads to new points being rendered for which we need to download data from the server.

**Comment by stackTom** [comment]
What do you think? Should we just disable on the fly re coloring when the user zooms/moves the map? And have a button so the user manually chooses when to re render at a given zoom level or after a map drag?

**Comment by falkamelung** [comment]
I think that is a good idea. Maybe we also have a button to switch the automatic recoloring on.  If on the other button disappears.

**Comment by stackTom** [comment]
> I think that is a good idea. Maybe we also have a button to switch the automatic recoloring on. If on the other button disappears.

Where do you want these buttons to go?

**Comment by falkamelung** [comment]
lets do upper right

**Comment by falkamelung** [comment]
The *.50 is back online. I just saw that we have something in the upper right. Rather lets put it next to the layer button

**Comment by falkamelung** [comment]
I am closing this for now. It worked very well the last few month.   It is certainly not priority 1. This was the result of other issues.  Maybe reconsider  at a later stage.
