### ISSUE TITLE
Velocity limits mismatch  between URL and display for temporal zoom-in

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#52]
Bug:
 The image below shows [0 40] but the URL has [0 20]. Maybe that occurs when a time period is selected (I have to dig into this a bit more)
```
https://insarmaps.miami.edu/start/19.4259/-155.5256/11.9681?flyToDatasetCenter=false&startDataset=S1_IW12_087_0527_0531_20180908_XXXXXXXX&pointLat=19.45602&pointLon=-155.58018&minScale=10&maxScale=-10&startDate=20210101&endDate=20210308&colorscale=velocity
```
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/11162588/135770811-fdf5db84-b065-4c25-8897-597d5cc2053d.png">

On the other hand, if I give [0 40] it displays it right,  but it shows [-10 10].

```
https://insarmaps.miami.edu/start/19.4259/-155.5256/11.9681?flyToDatasetCenter=false&startDataset=S1_IW12_087_0527_0531_20180908_XXXXXXXX&pointLat=19.45602&pointLon=-155.58018&minScale=0&maxScale=40&startDate=20210101&endDate=20210308&colorscale=velocity
```

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/11162588/135771161-630c3a7f-2a89-4d45-b6c5-87dc095f443f.png">

**Comment by stackTom** [comment]
There was a bug with updating the url minScale and maxScale. I've fixed this in: https://github.com/geodesymiami/insarmaps/commit/73465539a39d1a09345400530f7abe7fcc11f37d

Closing for now. If you see the issue again, please re-open, but I believe it is fixed.
