### ISSUE TITLE
intermediate  pixel sizes for display

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#55]
We have the "actual pixel size" option, but it is not quite right. When I select this option there are white space in between although there should not.

 It would be good to have some more options between the actual pixel size and the default size. E.g. a button to half or double the pixel size and/or to give the radius in meters, as well as smaller than actual pixel size.

It also will be good to display the pixel dimension (in x-direction) somewhere.  

It would be good to also have the ability to switch from circle to rectangle so that the whole area is covered when the actual pixel size is selected.

We never talked about map projectjections. Are we using Equirectangular?  If so a pixel should show up as a circle and a square pixel (we have lat-on squares) should show up as a square.  MapBox has options for that (see links)

https://www.mapbox.com/blog/adaptive-projections
https://en.wikipedia.org/wiki/Equirectangular_projection#/media/File:Plate_Carrée_with_Tissot's_Indicatrices_of_Distortion.svg

https://insarmaps.miami.edu/start/25.8786/-80.1209/16.8865?flyToDatasetCenter=false&startDataset=S1_IW3_048_0081_0082_20160927_20210703_PS040

<img width="904" alt="image" src="https://user-images.githubusercontent.com/11162588/172096987-90938fe0-bc72-4dfa-a081-a5dd923c658e.png">
<img width="807" alt="image" src="https://user-images.githubusercontent.com/11162588/172097055-96886dca-cef0-4853-829e-5e4e68320f90.png">

XXXXXXXXXXXXXXXXXXXX
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/11162588/172080048-93a12c14-9fa3-4249-8dee-559e236ce5ae.png">
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/11162588/172080090-2759e783-a078-4eea-8c41-76aed76ad1e3.png">

https://insarmaps.miami.edu/start/-7.5369/110.4420/15.6673?flyToDatasetCenter=false&startDataset=S1_IW2_076_0618_0621_20180110_XXXXXXXX_S07624_S07465_E110371_E110513&pointLat=-7.54070&pointLon=110.44117&minScale=-10&maxScale=10&startDate=20180110&endDate=20220113

**Comment by stackTom** [comment]
Please try this again. I have added support for it.

**Comment by stackTom** [comment]
Completed.
