### ISSUE TITLE
flyToDatasetCenter functionality does not work for high-res data

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#63]
The first command works (old S1 file), but the second does not work (new high-res S1 file):
```
https://insarmaps.miami.edu/start/26.0/-82.2101/8.0000?flyToDatasetCenter=true&startDataset=S1_IW1_128_0595_0597_20160605_XXXXXXXX&
https://insarmaps.miami.edu/start/26.0/-82.2101/8.0000?flyToDatasetCenter=true&startDataset=S1_IW3_048_0081_0082_20191111_20220710_PS&
```
I suspect this is because the  geographic information for not-geocode data is missing.   Can we retrieve this from the other arrays in the file? IIf the other layers don't have attributes,  can we use the latitude and longitude arrays?
```
HDF5 dataset "/HDFEOS/GRIDS/timeseries/geometry/latitude              ": shape (535, 794)          , dtype <float32>
HDF5 dataset "/HDFEOS/GRIDS/timeseries/geometry/longitude             ": shape (535, 794)          , dtype <float32>
```

**Comment by stackTom** [comment]
Fixed. Please git pull on the injest scripts. Note - you will have to re-ingest all the high res datasets. Any dataset that was ingested prior to the fix will not be able to support flyToDatasetCenter.
