### ISSUE TITLE
Do we need to show "Displacement time_series" string?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#65]
Sometime this string shows up. It can be annoying when you want to select a date. We don't need this I would think. Can we remove?

<img width="471" alt="image" src="https://user-images.githubusercontent.com/11162588/181935032-57ce2089-a9db-4461-91e2-45fe769fe6cd.png">

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/11162588/181934923-dbfcd2a3-c840-4398-8147-81d531c5031b.png">

**Comment by stackTom** [comment]
Fixed
