### ISSUE TITLE
Zooming-out looses all data

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#66]
Please display this data set:

http://129.213.120.104/start/25.8721/-80.1210/16.9441?flyToDatasetCenter=false&startDataset=S1_IW3_048_0081_0082_20191111_20220710_PS&pointLat=25.88298&pointLon=-80.12226&minScale=-0.4&maxScale=0.4&startDate=20191111&endDate=20220710

When you zoom out just a bit the data are lost. It would be good to be able to got at least 3 zoom levels down (or more).

**Comment by stackTom** [comment]
This is a feature from the past. Zoom out to disable at the zoom level you click on a dataset.
When we pass a zoom level via a url, it counts that at the zoom level you clicked at.
Should we change this?

**Comment by stackTom** [comment]
I see what you mean. It is annoying. I fixed it.
