### ISSUE TITLE
json_mbtiles2insarmaps.py  --available-space option

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#67]
It would be good to have this option to list the available disk space. Preferably It also lists the exact location where data are put as this is always a bit unclear

**Comment by stackTom** [comment]
Which script should I put this in?

**Comment by falkamelung** [comment]
into  `json_mbtiles2insarmaps.py` . It would be an option similar to `--list` or `--remove`

**Comment by stackTom** [comment]
Done. See: https://github.com/geodesymiami/insarmaps_scripts/commit/629d3b34aa778bac633d6dd9708f93a007eeca2d and https://github.com/geodesymiami/insarmaps/commit/93a4fb425047775b6115dac98f99b342a8728d66
