### ISSUE TITLE
Can the browser history show details?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#70]
Currently the browser history s not very useful (see below). Can we show more, e.g. when a new data set has been selected?    We probably want to do it in a smart way and omit history entries for unimportant changes if that is possible.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/11162588/182035226-e131fd8c-f333-4ff7-b4b9-9aea1707d03e.png">

**Comment by stackTom** [comment]
Done: https://github.com/geodesymiami/insarmaps/commit/2c99b4faadeb2a43515f526509167ac9d4b8cb8e

**Comment by falkamelung** [comment]
This is much more useful, but it shows a new history entry for everything, even if you only move slightly the area covered

<img width="435" alt="image" src="https://user-images.githubusercontent.com/11162588/182038636-67ed83d7-b320-45d2-8be1-026a8b92eabf.png">

It would be preferred to only create a history entry for major actions, such as (1) displaying a new dataset, (2) selecting a different time period.  We could also count "displaying a point" as major action but for now just (1) and possible (2) is OK (2 is lower priority)

**Comment by stackTom** [comment]
This is not possible. Unless we stop updating certain things like zoom, start coordinates, etc. For the url system to work, we use a function called replaceState and pushState. The browser creates a new history entry when these are used, there is no way around it.

See here: https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API#the_replacestate_method

**Comment by stackTom** [comment]
I use replaceState rather than pushState so we don't create a new history entry. But notice what it says in the documentation about replaceState "Note that this doesn't prevent the creation of a new entry in the global browser history."

**Comment by falkamelung** [comment]
I see. It is not a big deal. Then lets keep it as it now is.
