### ISSUE TITLE
Scrambling of display when ref point in URL

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#78]
When I display a point with a reference point in the URL it scrambles. In contrast, when the reference point is not in URL it works fine (I just re-ingested this dataset)

https://insarmaps.miami.edu/start/-0.8308/-91.1237/12.3923?flyToDatasetCenter=false&startDataset=S1_IW3_106_1177_1182_20161119_20180525&pointLat=-0.83569&pointLon=-91.12303&refPointLat=-0.84453&refPointLon=-91.11513&minScale=-14&maxScale=14&startDate=20180304&endDate=20180327&colorscale=displacement

https://insarmaps.miami.edu/start/-0.8308/-91.1237/12.3923?flyToDatasetCenter=false&startDataset=S1_IW3_106_1177_1182_20161119_20180525&pointLat=-0.83569&pointLon=-91.12303&minScale=-14&maxScale=14&startDate=20180304&endDate=20180327&colorscale=displacement

**Comment by stackTom** [comment]
Fixed it. Please keep playing and let me know if any more scrambling issues. Will close this issue if no more are seen in next day or two.

**Comment by falkamelung** [comment]
Yes, fixed.!thank you

**Comment by stackTom** [comment]
Have not seen this again. Closing.
