### ISSUE TITLE
For limited period, when ref point selected velocity not properly displayed

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#79]
If I first select a short time period and then a reference point the reference point is accepted ( time series is zero) but is is not shown by the color denoting 0. As the color scale goes from -112 to +112  zero displacement should be shown by green color and not orange as it currently is
 

https://user-images.githubusercontent.com/11162588/185471306-32b67b1e-1cdf-4e10-bce4-4cfec00dc3f1.mov

**Comment by stackTom** [comment]
Fixed. Closing this issue as it was a trivial bug (unlike the scrambling which is much more complex - I'm leaving that issue open until we can play with the site for a day or two).
