### ISSUE TITLE
Download as TXT button not working

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#81]
Just try. It gives you a scrambled output

https://insarmaps.miami.edu/start/25.8783/-80.1185/16.5978?flyToDatasetCenter=false&startDataset=S1_IW3_048_0081_0082_20150921_20211112_SM3_PS&pointLat=25.87826&pointLon=-80.12134&minScale=-1&maxScale=1&startDate=20150921&endDate=20211112

```
1/1
ErrorException in GeoJSONController.php line 373:
fopen(/var/www/html/insarmaps/storage/S1_IW3_048_0081_0082_20150921_20211112_SM3_PS.txt): failed to open stream: Permission denied
in GeoJSONController.php line 373
at HandleExceptions->handleError()
at fopen() in GeoJSONController.php line 373
at GeoJSONController->pointDataToTextFile()
at call_user_func_array() in Controller.php line 80
at Controller->callAction() in ControllerDispatcher.php line 146
at ControllerDispatcher->call() in ControllerDispatcher.php line 94

```

**Comment by stackTom** [comment]
Fixed. Was due to permissions getting screwed up on our server after all the apache fixes Darren had to make.

**Comment by falkamelung** [comment]
Unfortunately this does not work yet.  I get exactly the same error message
```
ErrorException in GeoJSONController.php line 373:
fopen(/var/www/html/insarmaps/storage/S1_IW3_048_0081_0082_20191111_20220710_PS.txt): failed to open stream: Permission denied
```

**Comment by stackTom** [comment]
That's weird. It worked when I fixed the permissions, but it stopped working again...

I've fixed the permissions again. Not sure why they got screwed up again. Will close this. Please reopen if the permissions get messed up again. It will point to a deeper issue that will need investigation.

**Comment by falkamelung** [comment]
Thank you. So if it happens again, just changing the permissions of `/var/www/html/insarmaps/storage`?

**Comment by stackTom** [comment]
Yes, but let me know if it happens again. As this shouldn't require constant changing of permissions. If it happens again, something deeper is going on.

**Comment by stackTom** [comment]
I know why it happened. I had to delete the website folder and re clone it from GitHub last week after I originally fixed it. So it shouldn't happen again.

Nevertheless, let me know if it does.
