### ISSUE TITLE
dataset window shows too many datasets

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#90]
I zoomed into Hawaii and it does show datasets that are not Hawaii. In the past it listed only datasets partly or fully included in the shown window.
<img width="535" alt="image" src="https://github.com/user-attachments/assets/a45a12c6-28a9-46c4-af8c-8d2e7fbafd93">

**Comment by stackTom** [comment]
This is due to one of the libraries we use, turf. For some reason, it is crashing now. I will have to see why, they probably changed their API and I must change the functions I used.

**Comment by stackTom** [comment]
Fixed with https://github.com/geodesymiami/insarmaps/commit/19e357611071484c2f1792011b55fb56f705316c
