### ISSUE TITLE
Can't deactivate reference point

### ISSUE THREAD

**Issue by stackTom** [geodesymiami/insarmaps#97]
Sometimes, once the Select Reference Point option is selected, the option remains active and there is no way to turn it off.

@disilvestro Do you know how to reproduce this?

**Comment by disilvestro** [comment]
Sorry, no idea

**Comment by disilvestro** [comment]
I don't have this problem anymore

**Comment by stackTom** [comment]
Sounds good. Please reopen this issue if you find the bug again.
