### ISSUE TITLE
Can't deselect second graph

### ISSUE THREAD

**Issue by stackTom** [geodesymiami/insarmaps#98]
When you show 2 timeseries together by choosing the option Second graph, once you deselect it, the second timeseries still runs in the background. What happens is that when you select a new point, the timeseries in the background(not visible) changes but not the visible one.

@disilvestro can you send me a video of this/steps to reproduce? I can't seem to trigger the bug.

**Comment by disilvestro** [comment]
I can't replicate it anymore, i'll keep you posted

**Comment by stackTom** [comment]
Sounds good, I can't either. Please re-open this issue if you find the bug again.
